baseURL = "https://inoccu.com/"
title = "INOUE, Ken'ichi"
canonifyURLs = true
paginate = 20

buildFuture = true

defaultContentLanguage = "ja"
hasCJKLanguage = true

theme = "coder-slasher"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusshortname = "inoccu"
googleAnalytics = "UA-2794204-22"

[taxonomies]
    category = "categories"
    tag = "tags"
