baseURL = "https://inoccu.com/"
title = "INOUE, Ken'ichi"
canonifyURLs = true
paginate = 20

buildFuture = true

defaultContentLanguage = "ja"
hasCJKLanguage = true

theme = "coder-slasher"

disqusshortname = "inoccu"
googleAnalytics = "UA-2794204-22"

[taxonomies]
    category = "categories"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4