[[main]]
name = "プロフィール"
weight = 1
url = "/profile/"

[[main]]
name = "執筆"
weight = 2
url = "/profile/writing.html"

[[main]]
name = "登壇"
weight = 3
url = "/profile/speaking.html"

[[main]]
name = "資料"
weight = 4
url = "/docs/"

[[main]]
name = "検索"
weight = 5
url = "/search/"

[[main]]
name = "お問い合わせ"
weight = 10
url = "/contact/"
